[web_server]
bind_address      = "192.168.1.136"
bind_port         = 8086

[mail]
smtp_endpoint     = "email-smtp.eu-north-1.amazonaws.com"
from              = "MyGridDeployer <peter.steneld@gridfire.org>"
to                = "Peter Steneld <peter.steneld@gmail.com>"

[github]
expected_repo_full_name = ["gostonefire/mygrid_dash","gostonefire/weatherlogger","gostonefire/mygrid_scheduler","gostonefire/mygrid","gostonefire/cloud_sync"]
deploy_script_path      = "/home/petste/MyDeployer/scripts/master_deploy.sh"

[general]
dev_dir           = "/home/petste/Develop"
scripts_dir       = "/home/petste/MyDeployer/scripts"
log_path          = "/home/petste/MyDeployer/logs/app.log"
log_level         = "Info"
log_to_stdout     = false
